services:
  # === DUCKDNS UPDATER ===
  ddns-updater:
    image: alpine:latest
    container_name: cinema_ddns
    restart: always
    command: >
      /bin/sh -c "
        apk add --no-cache curl bind-tools
        echo '✅ DuckDNS Updater Started'
        echo '🦆 Domain: cinema-plus.duckdns.org'
        while true; do
          echo '--- Updating DNS ---'
          # Токен здесь твой, из логов
          curl -s 'https://www.duckdns.org/update?domains=cinema-plus&token=12116d47-4a46-466d-940f-6989e40682e9&ip='
          sleep 300
        done
      "
    networks:
      - cinema-net

  # === APP ===
  backend:
    build: .
    container_name: cinema_backend
    restart: always
    expose:
      - "8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=light
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/CinemaPlus
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_DATA_REDIS_HOST=redis
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - CINEMA_INFRASTRUCTURE_LOKI_URL=http://loki:3100/ready
      - CINEMA_INFRASTRUCTURE_PROMETHEUS_URL=http://prometheus:9090/-/healthy
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - cinema-net

  frontend:
    build: ./frontend
    container_name: cinema_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cinema-net

  # === DATA ===
  postgres:
    image: 'postgres:15-alpine'
    container_name: cinema_postgres
    restart: always
    environment:
      - 'POSTGRES_DB=CinemaPlus'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d CinemaPlus" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cinema-net

  redis:
    image: 'redis:alpine'
    container_name: cinema_redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - cinema-net

  # === MONITORING ===
  prometheus:
    image: prom/prometheus:latest
    container_name: cinema_prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - cinema-net

  loki:
    image: grafana/loki:latest
    container_name: cinema_loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - cinema-net

  grafana:
    image: grafana/grafana:latest
    container_name: cinema_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data_prod:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - cinema-net

volumes:
  postgres_data_prod:
  grafana_data_prod:

networks:
  cinema-net:
    driver: bridge