spring:
  application:
    name: CinemaPlus

  docker:
    compose:
      lifecycle-management: start_only
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/CinemaPlus
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${MY_WSL_IP:localhost}
      port: 6379
      timeout: 2000ms


  kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        group-id: notification-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        admin:
        properties:
          request.timeout.ms: 5000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    root: INFO
#    org.springframework.security: DEBUG
    org.apache.kafka: WARN
    org.apache.zookeeper: WARN
    org.hibernate.SQL: INFO
    com.frytes.cinemaPlus: INFO

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000


cinema:
  # 1. Глобальные правила (Используются при реальной работе приложения)
  rules:
    lock-duration-minutes: 1     # Сколько держится бронь в Redis (BookingLockService)
    default-ads-minutes: 15       # Дефолт длительности рекламы (SessionService)
    default-cleanup-minutes: 20   # Дефолт длительности уборки (SessionService)

  # 2. Настройки для DataInitializer (Влияют ТОЛЬКО на генерацию демо-данных при старте)
  # Эти цены "запекаются" в базу данных как base_price сеанса
  demo-seeding:
    price-generation:
      base-morning: 250           # Цена для сеансов до 14:00
      base-evening: 450           # Цена для сеансов после 14:00

      # Набавка к базовой цене сеанса в зависимости от крутости зала
      hall-surcharges:
        red: 100                  # Красный зал
        blue: 100                 # Синий зал
        green: 0                  # Зеленый зал

  # 3. Настройки эмуляторов (Для тестов и демонстрации)
  mock:
    payment:
      delay-ms: 1000              # Имитация задержки банка
      fail-probability: 10        # Вероятность отказа (0-100%)