name: Deploy to Monoblock

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker compose -f compose.prod.yaml down -v 
          docker compose -f compose.prod.yaml up -d --build --remove-orphans
          docker image prune -f